### PR TITLE
Disable incremental compile for Scala projects

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

After upgrading Gradle to 7.1, we frequently see compile errors on Scala projects:
```
> Task :it:grpc:scala:compileTestScala
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:25: object hello is not a member of package com.linecorp.armeria.grpc.scala
did you mean Hello?
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:26: object hello is not a member of package com.linecorp.armeria.grpc.scala
did you mean Hello?
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:49: not found: type HelloServiceStub
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:91: not found: value HelloServiceGrpc
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:91: not found: type HelloServiceImpl
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:93: not found: type AuthError
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:94: value getMessage is not a member of Any
```
[Zinc](https://github.com/sbt/zinc)'s incremental compile seems not to work with Gradle 7.

Modifications:

- Disable incremental compile for Scala projects

Result:

Fix unexpected compile errors on Scala projects

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by trustin — COMMENTED** [review]
Thanks for looking into this, @ikhoon :bow:
