### ISSUE TITLE
Version Upgrade failure to 1.26.2 with spring 3.1.x

### ISSUE THREAD

**Issue by kwazii1231** [line/armeria#5304]
Hi recently i try to upgrade my armeria version to 1.26.2 with spring 3.x 
my application seems launch successfully with log open port 8080, 50051(gprc)

but when i try to make a connection to application with grpc stub or postman reflection 

it throw error like belows

```
[C] 2023-11-15T19:33:44.448+09:00|WARN|armeria-common-worker-kqueue-3-4||Exceptions.java:115|[id: 0xad4406ae, L:/[0:0:0:0:0:0:0:1%0]:50051 ! R:/[0:0:0:0:0:0:0:1%0]:65298][h1c] Unexpected exception:
java.lang.NoSuchMethodError: 'io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder com.linecorp.armeria.server.Http2ServerConnectionHandlerBuilder.decoderEnforceMaxRstFramesPerWindow(int, int)'
	at com.linecorp.armeria.server.Http2ServerConnectionHandlerBuilder.<init>(Http2ServerConnectionHandlerBuilder.java:45)
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator.newHttp2ConnectionHandler(HttpServerPipelineConfigurator.java:248)
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator.access$800(HttpServerPipelineConfigurator.java:108)
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator$Http2PrefaceOrHttpHandler.configureHttp2(HttpServerPipelineConfigurator.java:702)
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator$Http2PrefaceOrHttpHandler.decode(HttpServerPipelineConfigurator.java:671)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator$Http2PrefaceOrHttpHandler.channelInactive(HttpServerPipelineConfigurator.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:300)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

version 1.25.x not working like this.
so i think some change after 1.26.0 caused this problem.
i found some features from lease note
```
Server
  .builder()
  .http2MaxResetFramesPerWindow(100, 10)
  .build();
```
is this can make this problems?
please let me know how to handle this problems.
thanks!

**Comment by kwazii1231** [comment]
i think if support default value for this option
would help to prevent unexpected server failure of person who try to version upgrade like me

**Comment by jrhee17** [comment]
Hi, in general armeria has a tight dependency with netty so it is recommended that you match the version of Armeria with Netty.

https://github.com/line/armeria/blob/e59527529d9d49cc16aaaac0d1d32f1beaa05ae1/dependencies.toml#L87

Can you try with Netty version 4.1.100.Final?

**Comment by kwazii1231** [comment]
i also find bom of netty version 4.0 from guide page
i try to add that dependency and let you know the result!
i also try to see pr that i mentioned feature but it already have it's own default settings. so i also agree the reason is not from there

anyway! i will update after my try!
thanks for reply!

**Comment by kwazii1231** [comment]
@jrhee17 
```
    implementation(platform("io.netty:netty-bom:4.1.100.Final"))
    implementation("com.linecorp.armeria:armeria:$armeriaVersion")
    implementation("com.linecorp.armeria:armeria-spring-boot3-webflux-starter:$armeriaVersion")
    implementation("com.linecorp.armeria:armeria-grpc:$armeriaVersion")
```

this is what i used
but also same error shown

**Comment by jrhee17** [comment]
That's odd. If https://github.com/advisories/GHSA-xpw8-rcwv-8f8p is included than a `NoSuchMethodError` shouldn't be thrown.

What dependency management are you using? Can you confirm that the correct version is used at runtime? If gradle, I guess you can use something like `./gradlew dependencies`

**Comment by kwazii1231** [comment]
i found same issue as mine from stackoverflow
https://stackoverflow.com/questions/77307795/how-to-force-specific-version-of-a-transitive-dependency-netty-codec-http-in-g
it seems like spring dependency management plugin forced override netty version to 4.1.97
and my spring boot version is 3.1.3
after i upgrade spring boot version to 3.1.5 which described use netty 4.1.100 here (https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.coordinates)

after that it successfully fetch netty version 4.1.100 final...
i think this situation is not from here.
but every user who integrated with spring boot 3 should know!
now it's working find!

**Comment by Yang-33** [comment]
For spring-boot 2.x user:  we should use spring boot `2.7.17` even though armeria `1.26.3` depends on `2.7.16`.
