### ISSUE TITLE
0.99.5 micrometer-core-1.3.8.jar error

### ISSUE THREAD

**Issue by sokangmin** [line/armeria#2713]
When I updated to 0.99.5 with springboot webflux, the following error occurred.
The problem was solved by replacing micrometer-core-1.3.8.jar with micormeter-core-1.3.9.jar.

--------error-----------------------------------------------------------------
java.lang.NoSuchMethodError: io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics.monitor(Lio/micrometer/core/instrument/MeterRegistry;Ljava/util/concurrent/ScheduledExecutorService;Ljava/lang/String;Ljava/lang/String;[Lio/micrometer/core/instrument/Tag;)Ljava/util/concurrent/ScheduledExecutorService;
	at com.linecorp.armeria.server.ServerConfig.<init>(ServerConfig.java:159) ~[armeria-0.99.5.jar:na]

**Comment by ikhoon** [comment]
Micrometer version of Armeria is updated to 1.5.1 in 0.99.5. 
There is a Micrometer backward incompatibility issue. 
https://github.com/micrometer-metrics/micrometer/issues/2002
I think our workaround is right approach.

**Comment by trustin** [comment]
Please feel free to reopen if you need further assistance.
